-- Seed Serra Negra (gerado de src/data)
insert into public.categorias (id, slug, nome, descricao, icone, ordem) values
  ('cat-malhas', 'malhas', 'Malhas e tricô', 'Lojas de malha, tricô e moda de inverno no centro.', 'Shirt', 1),
  ('cat-couro', 'couro', 'Couro e acessórios', 'Bolsas, calçados, cinto e peças em couro.', 'ShoppingBag', 2),
  ('cat-artesanato', 'artesanato', 'Artesanato e presentes', 'Ateliês, souvenirs e presentes da serra.', 'Gift', 3),
  ('cat-hoteis', 'hoteis', 'Hotéis e pousadas', 'Onde dormir em Serra Negra no fim de semana.', 'BedDouble', 4),
  ('cat-restaurantes', 'restaurantes', 'Restaurantes e bares', 'Almoço, jantar e happy hour no centro.', 'UtensilsCrossed', 5),
  ('cat-cafeterias', 'cafeterias', 'Cafeterias e doces', 'Café, pão de queijo, chocolate e sobremesa.', 'Coffee', 6),
  ('cat-turismo-rural', 'turismo-rural', 'Turismo rural e experiências', 'Sítios, trilhas, cavalgada e fim de semana no campo.', 'Trees', 7),
  ('cat-saude', 'saude', 'Saúde e bem-estar', 'Clínicas, spa, farmácia de manipulação e terapias.', 'HeartPulse', 8),
  ('cat-servicos', 'servicos', 'Serviços locais', 'Oficina, farmácia, imobiliária, contábil e afins.', 'Wrench', 9),
  ('cat-eventos', 'eventos', 'Eventos e espaços', 'Salões, casas de festa e espaços para evento.', 'PartyPopper', 10);

insert into public.negocios (
  id, slug, nome, nome_fantasia, descricao, descricao_seo, categoria_id, tags,
  cep, logradouro, numero, complemento, bairro, cidade, uf, ponto_referencia,
  lat, lng, whatsapp, telefone, instagram, site_url, email, cnpj, horarios,
  aberto_feriado, fotos, logo_url, capa_url, plano, status, fonte_dados,
  aceita_whatsapp_comercial
) values
  ('neg-malharia-da-serra', 'malharia-da-serra', 'Malharia da Serra', 'Malharia da Serra', 'Malhas e tricô no centro. Tem tamanho grande, agasalho e peça para o frio da serra.', 'Loja de malhas em Serra Negra no centro, com tricô e agasalho.', 'cat-malhas', ARRAY['malha', 'tricô', 'inverno', 'gg']::text[], '13930-000', 'Rua Barão do Rio Branco', '412', null, 'Centro', 'Serra Negra', 'SP', 'Perto do calçadão', -22.6118, -46.7001, '5519999900001', '551936510001', 'malhariadaserra', null, null, null, '[{"dia":0,"abre":"09:00","fecha":"17:00","fechado":false},{"dia":1,"abre":"09:00","fecha":"18:30","fechado":false},{"dia":2,"abre":"09:00","fecha":"18:30","fechado":false},{"dia":3,"abre":"09:00","fecha":"18:30","fechado":false},{"dia":4,"abre":"09:00","fecha":"18:30","fechado":false},{"dia":5,"abre":"09:00","fecha":"18:30","fechado":false},{"dia":6,"abre":"09:00","fecha":"18:30","fechado":false}]'::jsonb, true, '{}'::text[], null, null, 'destaque', 'publicado', 'manual', true),
  ('neg-tricot-house', 'tricot-house', 'Tricot House', 'Tricot House', 'Cardigã, poncho e manta. Loja de malha com vitrine na rua principal.', 'Tricot House: malhas em Serra Negra.', 'cat-malhas', ARRAY['malha', 'poncho', 'cardigã']::text[], '13930-000', 'Avenida Prefeito Pedro Morganti', '180', null, 'Centro', 'Serra Negra', 'SP', null, -22.6129, -46.7014, '5519999900002', null, 'tricothousesn', null, null, null, '[{"dia":0,"abre":"09:00","fecha":"18:00","fechado":false},{"dia":1,"abre":"09:00","fecha":"19:00","fechado":false},{"dia":2,"abre":"09:00","fecha":"19:00","fechado":false},{"dia":3,"abre":"09:00","fecha":"19:00","fechado":false},{"dia":4,"abre":"09:00","fecha":"19:00","fechado":false},{"dia":5,"abre":"09:00","fecha":"19:00","fechado":false},{"dia":6,"abre":"09:00","fecha":"19:00","fechado":false}]'::jsonb, true, '{}'::text[], null, null, 'vitrine_plus', 'publicado', 'manual', true),
  ('neg-couro-e-cia', 'couro-e-cia', 'Couro & Cia', 'Couro & Cia', 'Bolsa, cinto, carteira e jaqueta. Couro da serra para levar na mala.', 'Loja de couro em Serra Negra.', 'cat-couro', ARRAY['couro', 'bolsa', 'cinto']::text[], '13930-247', 'Rua Sete de Setembro', '95', null, 'Centro', 'Serra Negra', 'SP', 'Em frente à praça', -22.6121, -46.6994, '5519999900003', null, 'couroeciasn', null, null, null, '[{"dia":0,"abre":"09:00","fecha":"16:00","fechado":false},{"dia":1,"abre":"09:00","fecha":"18:00","fechado":false},{"dia":2,"abre":"09:00","fecha":"18:00","fechado":false},{"dia":3,"abre":"09:00","fecha":"18:00","fechado":false},{"dia":4,"abre":"09:00","fecha":"18:00","fechado":false},{"dia":5,"abre":"09:00","fecha":"18:00","fechado":false},{"dia":6,"abre":"09:00","fecha":"18:00","fechado":false}]'::jsonb, true, '{}'::text[], null, null, 'destaque', 'publicado', 'manual', true),
  ('neg-atelie-das-aguas', 'atelie-das-aguas', 'Ateliê das Águas', null, 'Cerâmica, tecido e presente feito em Serra Negra.', 'Artesanato e presentes em Serra Negra.', 'cat-artesanato', ARRAY['artesanato', 'presente', 'cerâmica']::text[], '13930-000', 'Rua das Hortênsias', '22', null, 'Estância Suíça', 'Serra Negra', 'SP', null, -22.6146, -46.7028, '5519999900004', null, 'ateliedasaguas', null, null, null, '[{"dia":0,"abre":"10:00","fecha":"16:00","fechado":false},{"dia":1,"abre":"10:00","fecha":"18:00","fechado":false},{"dia":2,"abre":"10:00","fecha":"18:00","fechado":false},{"dia":3,"abre":"10:00","fecha":"18:00","fechado":false},{"dia":4,"abre":"10:00","fecha":"18:00","fechado":false},{"dia":5,"abre":"10:00","fecha":"18:00","fechado":false},{"dia":6,"abre":"10:00","fecha":"18:00","fechado":false}]'::jsonb, false, '{}'::text[], null, null, 'gratis', 'publicado', 'indicacao', true),
  ('neg-pousada-alto-da-serra', 'pousada-alto-da-serra', 'Pousada Alto da Serra', 'Pousada Alto da Serra', 'Quartos com vista, café da manhã e silêncio depois do comércio.', 'Pousada em Serra Negra no Alto da Serra.', 'cat-hoteis', ARRAY['pousada', 'vista', 'café da manhã']::text[], '13930-000', 'Estrada do Alto da Serra', '1500', null, 'Alto da Serra', 'Serra Negra', 'SP', 'Subindo depois do Cristo', -22.6084, -46.7058, '5519999900005', '551936510105', 'pousadaaltodaserra', null, null, null, '[{"dia":0,"abre":"08:00","fecha":"22:00","fechado":false},{"dia":1,"abre":"08:00","fecha":"22:00","fechado":false},{"dia":2,"abre":"08:00","fecha":"22:00","fechado":false},{"dia":3,"abre":"08:00","fecha":"22:00","fechado":false},{"dia":4,"abre":"08:00","fecha":"22:00","fechado":false},{"dia":5,"abre":"08:00","fecha":"22:00","fechado":false},{"dia":6,"abre":"08:00","fecha":"22:00","fechado":false}]'::jsonb, true, '{}'::text[], null, null, 'destaque', 'publicado', 'manual', true),
  ('neg-hotel-termas', 'hotel-termas-serra-negra', 'Hotel Termas Serra Negra', 'Hotel Termas', 'Hotel no centro, bom para quem vem comprar malha e quer andar a pé.', 'Hotel em Serra Negra no centro.', 'cat-hoteis', ARRAY['hotel', 'centro', 'termas']::text[], '13930-000', 'Rua Joaquim Magalhães', '78', null, 'Centro', 'Serra Negra', 'SP', null, -22.6112, -46.7018, '5519999900006', null, 'hoteltermassn', null, null, null, '[{"dia":0,"abre":"00:00","fecha":"23:59","fechado":false},{"dia":1,"abre":"00:00","fecha":"23:59","fechado":false},{"dia":2,"abre":"00:00","fecha":"23:59","fechado":false},{"dia":3,"abre":"00:00","fecha":"23:59","fechado":false},{"dia":4,"abre":"00:00","fecha":"23:59","fechado":false},{"dia":5,"abre":"00:00","fecha":"23:59","fechado":false},{"dia":6,"abre":"00:00","fecha":"23:59","fechado":false}]'::jsonb, true, '{}'::text[], null, null, 'vitrine_plus', 'publicado', 'manual', true),
  ('neg-emporio-da-montanha', 'emporio-da-montanha', 'Empório da Montanha', null, 'Almoço de serra, prato executivo durante a semana e fila no domingo.', 'Restaurante em Serra Negra no centro.', 'cat-restaurantes', ARRAY['almoço', 'serra', 'família']::text[], '13930-000', 'Rua Coronel Ataliba Camargo', '310', null, 'Centro', 'Serra Negra', 'SP', 'Esquina com o calçadão', -22.6134, -46.7005, '5519999900007', null, 'emporiodamontanha', null, null, null, '[{"dia":0,"abre":"11:00","fecha":"16:30","fechado":false},{"dia":1,"abre":"11:00","fecha":"16:00","fechado":false},{"dia":2,"abre":"11:00","fecha":"16:00","fechado":false},{"dia":3,"abre":"11:00","fecha":"16:00","fechado":false},{"dia":4,"abre":"11:00","fecha":"16:00","fechado":false},{"dia":5,"abre":"11:00","fecha":"16:00","fechado":false},{"dia":6,"abre":"11:00","fecha":"16:00","fechado":false}]'::jsonb, true, '{}'::text[], null, null, 'destaque', 'publicado', 'manual', true),
  ('neg-cafe-do-lago', 'cafe-do-lago', 'Café do Lago', 'Café do Lago', 'Café, bolo caseiro e chocolate quente depois da volta nas lojas.', 'Cafeteria em Serra Negra.', 'cat-cafeterias', ARRAY['café', 'bolo', 'chocolate']::text[], '13930-000', 'Avenida João XXIII', '50', null, 'Centro', 'Serra Negra', 'SP', 'De frente para o lago', -22.6104, -46.6991, '5519999900008', null, 'cafedolago.sn', null, null, null, '[{"dia":0,"abre":"08:00","fecha":"19:00","fechado":false},{"dia":1,"abre":"08:00","fecha":"19:00","fechado":false},{"dia":2,"abre":"08:00","fecha":"19:00","fechado":false},{"dia":3,"abre":"08:00","fecha":"19:00","fechado":false},{"dia":4,"abre":"08:00","fecha":"19:00","fechado":false},{"dia":5,"abre":"08:00","fecha":"19:00","fechado":false},{"dia":6,"abre":"08:00","fecha":"19:00","fechado":false}]'::jsonb, true, '{}'::text[], null, null, 'gratis', 'publicado', 'manual', true),
  ('neg-sitio-experiencia', 'sitio-experiencia-rural', 'Sítio Experiência Rural', null, 'Visita, café colonial e trilha leve na zona rural de Serra Negra.', 'Turismo rural em Serra Negra.', 'cat-turismo-rural', ARRAY['sítio', 'café colonial', 'trilha']::text[], '13930-000', 'Estrada Municipal dos Pinheiros', 's/n', null, 'Zona rural', 'Serra Negra', 'SP', 'Km 4 da municipal', -22.6215, -46.6884, '5519999900009', null, 'sitioexperienciarural', null, null, null, '[{"dia":0,"abre":"09:00","fecha":"16:00","fechado":false},{"dia":1,"abre":"09:00","fecha":"17:00","fechado":false},{"dia":2,"abre":"09:00","fecha":"17:00","fechado":false},{"dia":3,"abre":"09:00","fecha":"17:00","fechado":false},{"dia":4,"abre":"09:00","fecha":"17:00","fechado":false},{"dia":5,"abre":"09:00","fecha":"17:00","fechado":false},{"dia":6,"abre":"09:00","fecha":"17:00","fechado":false}]'::jsonb, true, '{}'::text[], null, null, 'destaque', 'publicado', 'manual', true),
  ('neg-espaco-bem-estar', 'espaco-bem-estar-serra', 'Espaço Bem-Estar Serra', null, 'Massagem, day spa e um respiro depois da subida da serra.', 'Spa e bem-estar em Serra Negra.', 'cat-saude', ARRAY['spa', 'massagem', 'bem-estar']::text[], '13930-000', 'Rua Helvetia', '88', null, 'Estância Suíça', 'Serra Negra', 'SP', null, -22.6152, -46.7039, '5519999900010', null, 'bemestarsn', null, null, null, '[{"dia":0,"abre":null,"fecha":null,"fechado":true},{"dia":1,"abre":"09:00","fecha":"19:00","fechado":false},{"dia":2,"abre":"09:00","fecha":"19:00","fechado":false},{"dia":3,"abre":"09:00","fecha":"19:00","fechado":false},{"dia":4,"abre":"09:00","fecha":"19:00","fechado":false},{"dia":5,"abre":"09:00","fecha":"19:00","fechado":false},{"dia":6,"abre":"09:00","fecha":"19:00","fechado":false}]'::jsonb, false, '{}'::text[], null, null, 'gratis', 'publicado', 'manual', true),
  ('neg-farmacia-central', 'farmacia-central-serra-negra', 'Farmácia Central', 'Farmácia Central', 'Farmácia de rua no centro, com plantão no fim de semana.', 'Farmácia em Serra Negra no centro.', 'cat-servicos', ARRAY['farmácia', 'plantão', 'centro']::text[], '13930-000', 'Rua Barão do Rio Branco', '100', null, 'Centro', 'Serra Negra', 'SP', 'Esquina da igreja', -22.6126, -46.6988, '5519999900011', '551936510200', null, null, null, null, '[{"dia":0,"abre":"08:00","fecha":"20:00","fechado":false},{"dia":1,"abre":"08:00","fecha":"20:00","fechado":false},{"dia":2,"abre":"08:00","fecha":"20:00","fechado":false},{"dia":3,"abre":"08:00","fecha":"20:00","fechado":false},{"dia":4,"abre":"08:00","fecha":"20:00","fechado":false},{"dia":5,"abre":"08:00","fecha":"20:00","fechado":false},{"dia":6,"abre":"08:00","fecha":"20:00","fechado":false}]'::jsonb, true, '{}'::text[], null, null, 'gratis', 'publicado', 'manual', true),
  ('neg-salao-circuito', 'salao-circuito-das-aguas', 'Salão Circuito das Águas', null, 'Espaço para festa, confraternização e evento de temporada.', 'Salão de eventos em Serra Negra.', 'cat-eventos', ARRAY['evento', 'festa', 'salão']::text[], '13930-000', 'Rua das Palmeiras', '640', null, 'Centro', 'Serra Negra', 'SP', null, -22.6141, -46.6976, '5519999900012', null, 'salaocircuito', null, null, null, '[{"dia":0,"abre":"10:00","fecha":"16:00","fechado":false},{"dia":1,"abre":"09:00","fecha":"18:00","fechado":false},{"dia":2,"abre":"09:00","fecha":"18:00","fechado":false},{"dia":3,"abre":"09:00","fecha":"18:00","fechado":false},{"dia":4,"abre":"09:00","fecha":"18:00","fechado":false},{"dia":5,"abre":"09:00","fecha":"18:00","fechado":false},{"dia":6,"abre":"09:00","fecha":"18:00","fechado":false}]'::jsonb, true, '{}'::text[], null, null, 'gratis', 'publicado', 'manual', true);
